### ISSUE TITLE
compare url against a baseline

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-perf#292]
add support for comparing performance metrics between two sites! The result being; that degraded performance can be detected and reported!

**Comment by trieloff** [comment]
I just had a look at this. Right now, the service just takes an array of test specs and the comparison against the threshold is done in helix-cli.

I suggest we do the same for the baseline comparison, but you can start by building a prototype test script in helix-pages. Once we feel it’s stable there, we implement a generalized version in helix-cli.

**Comment by MarquiseRosier** [comment]
Ohh right!, I just realized this too. I like that plan, thank you for the guidance here! 


https://github.com/adobe/helix-cli/blob/cc3c87159f608d32c0f0429a6ec9bfb080105782/src/perf.cmd.js#L147-L161
