### ISSUE TITLE
e is not a function error during deployment (only observed by Epsagon)

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-perf#47]
EpsagonAPP   [8 hours ago]
> e is not a function
> Entity
> /helix/helix-services/perf@ci412
> Type
> TypeError
> Occurrences (24 Hours)
> 1
> Application
> Helix Services
> Epsagon Traces | Yesterday at 11:36 PM

@rofe  [7 hours ago]
> helix-perf@412 was green in CircleCI, same as the last occurrence @410, both triggered by greenkepper. looks to me like this error is expected to happen in the test? @trieloff

Lars Trieloff  [2 minutes ago]
> No, this error is definitely unexpected. It happens in the “Branch Deployment” step of https://circleci.com/gh/adobe/helix-perf/412 when a HTTP request is made to the newly deployed function.

Lars Trieloff  [1 minute ago]
> My guess: as we set the `CALIBRE_TOKEN` only in the next step, `init` call fails for the first request, which causes this issue.

**Comment by tripodsan** [comment]
I added the `CALIBRE_TOKEN` to the helix-services package. hope this helps.

**Comment by rofe** [comment]
we just had another error like this with build 421

**Comment by tripodsan** [comment]
fixed it.
